# Ligand Scoring
ligand_scores = {
    'APP': ['App'],
    'CADM': ['Cadm1', 'Cadm3'],
    'CCL': ['Ccl1', 'Ccl12', 'Ccl17', 'Ccl2', 'Ccl22', 'Ccl24', 'Ccl25', 'Ccl3', 'Ccl4', 'Ccl5', 'Ccl6', 'Ccl7', 'Ccl8', 'Ccl9'],
    'CD34': ['Cd34'],
    'CD45': ['Ptprc'],
    'CD86': ['Cd86'],
    'CDH': ['Cdh15', 'Cdh1', 'Cdh2', 'Cdh4'],
    'COMPLEMENT': ['C4a', 'Hc', 'C3'],
    'CSF': ['Csf1', 'Il34'],
    'CXCL': ['Cxcl1', 'Cxcl10', 'Cxcl11', 'Cxcl13', 'Cxcl16', 'Cxcl2', 'Cxcl5', 'Cxcl9', 'Pf4', 'Ppbp'],
    'GALECTIN': ['Lgals9'],
    'GRN': ['Grn'],
    'ICAM': ['Icam1', 'Icam2'],
    'IL6': ['Il6', 'Il11', 'Il31'],
    'ITGAL_ITGB2': ['Itgal', 'Itgb2', 'Itgb2l'],
    'JAM': ['Jam2', 'Jam3', 'F11r'],
    'LAMININ': ['Lama5', 'Lamb2', 'Lamb3', 'Lamc1', 'Lamc2'],
    'MIF': ['Mif'],
    'PARs': ['Prss2', 'Ctsg', 'Gzma'],
    'PECAM1': ['Pecam1'],
    'PROS': ['Pros1'],
    'SELL': ['Sell'],
    'SELPLG': ['Selplg'],
    'SEMA4': ['Sema4a', 'Sema4c', 'Sema4d'],
    'SEMA7': ['Sema7a'],
    'SPP1': ['Spp1'],
    'THBS': ['Thbs3', 'Thbs2', 'Thbs1', 'Thbs4'],
    'THY1': ['Thy1'],
    'VWF': ['Vwf']
}
#Receptor Scoring
receptor_scores = {
    'APP': ['Cd74'],
    'CADM': ["Cadm1", 'Cadm3'],
    'CCL': ['Ccr2', 'Ccr1l1', 'Ccr4', 'Ccr1', 'Ccr3', 'Ackr1', 'Ccr5', 'Ccr9'],
    'CD34': ['Selp'],
    'CD45': ['Mrc1', 'Cd22'],
    'CD86': ['Cd28'],
    'CDH': ['Cdh15', 'Cdh1', 'Cdh2', 'Cdh4'],
    'COMPLEMENT': ['Itgax', 'C3ar1', 'Itgam', 'Itgb2', 'Cr2', 'C5ar1'],
    'CSF': ['Csf1r'],
    'CXCL': ['Cxcr2', 'Cxcr1', 'Cxcr3', 'Cxcr5', 'Ackr1', 'Cxcr6'],
    'GALECTIN': ['Cd44', 'Ptprc', 'Havcr2', 'Ighm'],
    'GRN': ['Sort1'],
    'ICAM': ['Itgal', 'Itgam', 'Itgax', 'Itgb2', 'Itgb2l', 'Spn'],
    'IL6': ['Il11ra1', 'Il6r', 'Il6st', 'Il31ra', 'Osmr'],
    'ITGAL_ITGB2': ['Icam1', 'Icam2', 'Cd226'],
    'JAM': ['F11r', 'Itgam', 'Itgb2', 'Itgal', 'Jam2', 'Itgb2l', 'Jam3', 'Itga3', 'Itgb1', 'Itgav'],
    'LAMININ': ['Cd44', 'Dag1', 'Itga1', 'Itga2', 'Itga3', 'Itga6', 'Itga7', 'Itga9', 'Itgav', 'Itgb1', 'Itgb8', 'Sv2a', 'Sv2b', 'Sv2c'],
    'MIF': ['Cd74', 'Cd44', 'Cxcr2', 'Cxcr4'],
    'PARs': ['F2r', 'F2rl3', 'F2rl2'],
    'PECAM1': ['Pecam1'],
    'PROS': ['Axl', 'Tyro3'],
    'SELL': ['Cd34', 'Podxl'],
    'SELPLG': ['Selp', 'Sell'],
    'SEMA4': ['Nrp1', 'Plxna2', 'Plxna3', 'Plxnb2', 'Cd72', 'Plxna1', 'Plxnb3', 'Timd2', 'Plxna4'],
    'SEMA7': ['Itgb1', 'Itga1', 'Plxnc1'],
    'SPP1': ['Cd44', 'Itga4', 'Itga5', 'Itga8', 'Itga9', 'Itgav', 'Itgb1', 'Itgb3', 'Itgb5', 'Itgb6'],
    'THBS': ['Cd36', 'Cd47', 'Sdc1', 'Itgav', 'Itgb3', 'Sdc4', 'Itga3', 'Itgb1'],
    'THY1': ['Itgam', 'Itgb2', 'Itgax', 'Itgav', 'Itgb3'],
    'VWF': ['Itgav', 'Itgb3', 'Itga2b', 'Itgb3', 'Gp1ba', 'Gp1bb', 'Gp5', 'Gp9']
}
